### ISSUE TITLE
Validate all product create workflows

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui-library#464]
- [x] IP Peer
  - [x] Customer not disabled: see https://github.com/workfloworchestrator/orchestrator-ui-library/issues/721 
- [x] IP Peer Group
- [x] IP Peer Port
  - see #721  
- [x] IP Prefix
Niet vertaald see #728
![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/447a8b82-a479-4a42-8a2f-c272e1d87a3a)

pydanticForms.widgets.ipvAnyNetworkField.manuallySelectedPrefix --> Manually selected prefix

- [x] NSI LightPath
- [x] SN8 Aggregated Service Port
- [x] SN8 Corelink
  - [x] Customer not disabled: see https://github.com/workfloworchestrator/orchestrator-ui-library/issues/721 
- [x] SN8 IRB Service Port
  - [x] Same as IP Peer port, customer drop down is not disabled. see #721 
  - [x] Node dropdown is not filtering terminated subscriptions see #725 
- [x] SN8 L2VPN
  - [x] see [#729](https://github.com/workfloworchestrator/orchestrator-ui-library/issues/729)
- [x] SN8 L3VPN - Broken!
  - [x] not possible to select ports on the second page
- [x] SN8 LightPath
  - [x] dropdown list terminated ports
- [x] SN8 LightPath Redundant
- [x] SN8 MSC
- [x] SN8 Node
  - [x] Customer not disabled: see https://github.com/workfloworchestrator/orchestrator-ui-library/issues/721 
- [x] SN8 NSISTP
- [x] SN8 Service Port 10G
- [x] SN8 SURFinternet BGP
   - [x] see #683  
- [x] SN8 SURFinternet Static
- [x] SURFfirewall V2 1 Gbit/s Redundant
  - [x] see #723 
- [x] SURFwireless
